name: Check structure

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    name: Get repository and check if structure is correct
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Check structure
      run: |
        python3 check_structure.py
